### ISSUE TITLE
licence is wrong

### ISSUE THREAD

**Issue by virtuoso** [virtuoso/koowaldah#5]
Per common agreement, distribution licence as well as individual code files' licence should be changed to GPLv2.

**Comment by xl0** [comment]
ACK.

**Comment by virtuoso** [comment]
Check out the new-history branch: https://github.com/virtuoso/koowaldah/tree/new-history

**Comment by virtuoso** [comment]
Licences changed after "0.0.3" commit.

**Comment by virtuoso** [comment]
Changes are in master. Closing.
